[build]
builder = "nixpacks"

[build.nixpacksInstallCmd]
cmd = "bun install"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
